This notebook will show how PCA works without the sklearn Class

In [1]:
import pandas as pd
import numpy as np


In [2]:
df= pd.read_csv("./datasets/pca_data.csv")

In [3]:
df.head()

,x1,x2,x3,y
0,2.5,2.4,5.1,0
1,0.5,0.7,1.2,0
2,2.2,2.9,5.0,1
3,1.9,2.2,4.3,1
4,3.1,3.0,6.2,1


In [4]:
#mean centering

mean1= df['x1'].mean()
mean2= df['x2'].mean()
mean3= df['x3'].mean()


sd1= df['x1'].std()
sd2= df['x2'].std()
sd3= df['x3'].std()

In [5]:
mean_centered_values= {
    '0': np.array([(x-mean1)/sd1 for x in df['x1']]),
    '1': np.array([(x-mean2)/sd2 for x in df['x2']]),
    '2': np.array([(x-mean3)/sd3 for x in df['x3']]),
}

In [6]:
for i in range(3):
    df.iloc[:, i]= mean_centered_values[f'{i}']

In [7]:
df= df.round(2)

In [8]:
df

,x1,x2,x3,y
0,0.70,0.42,0.54,0
1,-1.88,-1.67,-1.80,0
2,0.31,1.03,0.48,1
3,-0.08,0.17,0.06,1
4,1.47,1.15,1.20,1
5,0.44,0.79,0.78,0
6,0.05,-0.56,-0.12,0
7,-1.24,-1.18,-1.26,0
8,-0.59,-0.56,-0.60,1
9,-1.11,-1.42,-1.32,0


In [9]:
x= df.iloc[:, :-1]
x.head()



,x1,x2,x3
0,0.70,0.42,0.54
1,-1.88,-1.67,-1.80
2,0.31,1.03,0.48
3,-0.08,0.17,0.06
4,1.47,1.15,1.20


In [10]:
x.cov()

,x1,x2,x3
x1,0.999514,0.945286,0.986914
x2,0.945286,0.999084,0.978557
x3,0.986914,0.978557,1.001829


In [11]:
cov_matrix = x.cov().values
cov_matrix.round(2
                 )

array([[1.  , 0.95, 0.99],
       [0.95, 1.  , 0.98],
       [0.99, 0.98, 1.  ]])

In [12]:
# find the eigen vector and eigen value of cov matrix
eigen_value, eigen_vector= np.linalg.eig(cov_matrix)

In [13]:
eigen_vector

array([[-0.5756018 , -0.663868  , -0.4774535 ],
       [-0.57382953,  0.74389529, -0.34254849],
       [-0.58258239, -0.07680539,  0.80913453]])

In [14]:
eigen_value

array([2.94077254, 0.05445705, 0.00519708])

    - finally conveting the above 3 dim array into 2d. For 2d, we need two eigen vector and for 1d we need 1 eigen vector


In [15]:
x.shape

(15, 3)

In [16]:
transformers= np.array([eigen_vector[0],eigen_vector[1]])

In [17]:
transformers

array([[-0.5756018 , -0.663868  , -0.4774535 ],
       [-0.57382953,  0.74389529, -0.34254849]])

In [18]:
reduced_dim= np.dot(x.values, transformers.T)

In [19]:
pd.DataFrame(reduced_dim, columns=['PC1', 'PC2'])

,PC1,PC2
0,-0.939571,-0.274221
1,3.050207,0.453082
2,-1.091398,0.423902
3,-0.095457,0.151816
4,-2.182527,-0.399108
5,-1.150134,0.068004
6,0.400280,-0.404167
7,2.098702,0.265363
8,0.997843,0.127507
9,2.211849,0.032783
