In [1]:
import numpy as np

In [10]:
#create a array(tensor) using numpy
zerodtensor= np.array(4)

In [11]:
zerodtensor

array(4)

In [12]:
#know the dimension of given array
zerodtensor.ndim

0

In [13]:
onedtensor= np.array([1, 2, 3, 4])

In [14]:
onedtensor

array([1, 2, 3, 4])

In [16]:
onedtensor.ndim

1

In [17]:
threedtensor= np.array([[1,2,3], [4,5,6], [7,8,9]])

In [18]:
threedtensor

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
threedtensor.ndim

2

In [22]:
threedtensor= np.array(
    [
        [[0,1], [2,3], [4,5]],
        [[6,7], [8,9], [0,1]]
    ]
)

In [24]:
threedtensor

array([[[0, 1],
        [2, 3],
        [4, 5]],

       [[6, 7],
        [8, 9],
        [0, 1]]])

In [25]:
threedtensor.ndim

3

Basically, 1d tensor is a collection of 0 d tensor.
2D tensor is collection of 1D tensor
3D tensor is collection of 2D tensors and so on

